#!/bin/bash
#title           :service
#description     :This script will start the server
#author		       :dodiaraculus17
#date            :20161101
#version         :0.1    
#usage		       :service webister
#notes           :
#bash_version    :4.1.5(1)-release
#==============================================================================
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root! Please contact Adaclare, if you are experiencing errors." 1>&2
   exit 1
fi
case "$1" in
  start)
    echo -n $"Starting webister daemon: "
    cd /var/webister/80 && sudo php -S 0.0.0.0:8080 &>/dev/null &
    cd /var/webister/interface && sudo php -S 0.0.0.0:8081 &>/dev/null &
    mysql --batch --raw -u root -p$(php /etc/init.d/grabpass.php) -hlocalhost -Dwebister -e'SELECT port FROM `Users`' | while read MM; do
    fgd="port"
    if [ "$MM" != "$fgd" ]; then
    if [ ! -d /var/webister/$MM ]; then
    echo "$MM did not exist so creating it"
    mkdir -p /var/webister/$MM;
    fi
    cd /var/webister/ && php -S 0.0.0.0:$MM &>/dev/null &
    fi
    done
    ;;

  stop)
    # Stop daemons.
    echo -n $"Shutting down webister "
    pkill -u webister
    #service mysql stop No need
    echo

    # Do clean-up works here like removing pid files from /var/run, etc.
    ;;
  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
