#!/bin/bash
#title           :service
#description     :This script will start the server
#author		       :dodiaraculus17
#date            :20161101
#version         :0.1    
#usage		       :service webister
#notes           :
#bash_version    :4.1.5(1)-release
#==============================================================================
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root! Please contact Adaclare, if you are experiencing errors." 1>&2
   exit 1
fi
case "$1" in
  start)
    sudo nohup php /etc/init.d/grabpass.php  &>/dev/null &
    sudo nohup python /var/webister/ftpserv.py &>/dev/null &
    ;;

  stop)
    # Stop daemons.
    echo -n $"Shutting down webister "
    sudo killall php
    sudo killall python
    #service mysql stop No need
    echo

    # Do clean-up works here like removing pid files from /var/run, etc.
    ;;
  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
