#!/bin/bash
#title           :build
#description     :This script will compile the code and create the files
#author		       :dodiaraculus17
#date            :20161101
#version         :0.1    
#usage		       :./build or sudo ./build
#notes           :
#bash_version    :4.1.5(1)-release
#==============================================================================
#Important Version Variables
VERSION="5.0.0"
preparebar() {
# $1 - bar length
# $2 - bar char
    barlen=$1
    barspaces=$(printf "%*s" "$1")
    barchars=$(printf "%*s" "$1" | tr ' ' "$2")
}
progressbar() {
# $1 - number (-1 for clearing the bar)
# $2 - max number
    if [ $1 -eq -1 ]; then
        printf "\r  $barspaces\r"
    else
        barch=$(($1*barlen/$2))
        barsp=$((barlen-barch))
        printf "\r[%.${barch}s%.${barsp}s]\r" "$barchars" "$barspaces"
    fi
}
spinner()
{
    local pid=$!
    local delay=0.75
    local spinstr='+-!;&'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}
echo
	echo
	echo "STAGE 1"
	echo "====================================================================="
	echo
	echo "--------------------Webister INSTALLER $VERSION----------------------"
	echo "-------------------------www.adaclare.com----------------------------"
	echo "---------------------------------------------------------------------"
	echo
	echo
#Show the title screen
echo "       d8888     888                888                       "
echo "      d88888     888                888                       "
echo "     d88P888     888                888                       "
echo "    d88P 888 .d88888 8888b.  .d8888b888 8888b. 888d888 .d88b. "
echo "   d88P  888d88  888     88bd88P    888      88b888P  d8P  Y8b"
echo "  d88P   888888  888.d888888888     888.d888888888    88888888"
echo " d8888888888Y88b 888888  888Y88b.   888888  888888    Y8b.    "
echo " d88P     888  Y88888 Y888888  Y8888P888 Y888888888      Y8888"
preparebar 50 "#"
echo "You are installing tecflare webister version $VERSION"
echo "Validating Random Website Test..."
# Feel Free to add your website below




websites[0]="http://donate.adaclare.com"
websites[1]="http://www.adaclare.com"
websites[2]="http://www.cloudflare.com"
websites[3]="http://www.google.com"
websites[4]="http://www.php.net"
random=$(( ( RANDOM % 4 )  + 0 ))
website=${websites[$random]}
random=$(( ( RANDOM % 4 )  + 0 ))
website_one=${websites[$random]}
random=$(( ( RANDOM % 4 )  + 0 ))
website_two=${websites[$random]}
if curl --output /dev/null --silent --head --fail "$website"; then
  printf '%s\n' "$website is ok"
else
  printf '%s\n' "$website did not pass"
  exit 1;
fi
if curl --output /dev/null --silent --head --fail "$website_one"; then
  printf '%s\n' "$website_one is ok"
else
  printf '%s\n' "$website_one did not pass"
  exit 1;
fi
if curl --output /dev/null --silent --head --fail "$website_two"; then
  printf '%s\n' "$website_two is ok"
else
  printf '%s\n' "$website_two did not pass"
  exit 1;
fi
fqdn=""
echo -e "Validation Complete"

echo "Checking for other web hosting control panels..."
if [ -e /usr/local/cpanel ] || [ -e /usr/local/directadmin ] || [ -e /usr/local/solusvm/www ] || [ -e /usr/local/home/admispconfig ] || [ -e /usr/local/lxlabs/kloxo ] || [ -e /var/webister ]; then
    echo -e "It appears that a control panel is already installed on your server"
    echo -e "This may create issues with the installer, CONTINUING..."
    
fi
echo -e "Clean OS Detected"

echo "Licence Verification"
echo "Ex: XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX"
echo "If the key is not correct, you will get an error."
echo "Enter Licence Now:"
read key
cd /tmp/webister/ 
EEE=$(unzip -P "$key" interface.zip)
if [[ $EEE =~ .*incorrect.* ]]
then
echo "The licence was incorrect, please try again or contact support."
exit 1
fi
service mysql start & spinner
read -p "Do you want to configure mysql? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    mysql_secure_installation
fi
echo -e "\nEnter the password for mysql please(It is usually nothing):"

read PASS;
progressbar 1 20
BLAH=$(mysql -u root -p"$PASS" -e "CREATE DATABASE webister;") & spinner
progressbar 2 20
BLAH=$(id -u webister &>/dev/null || useradd webister) & spinner
progressbar 3 20
BLAH=$(mkdir -p /var/webister) & spinner
progressbar 4 20
BLAH=$(cp -r interface /var/webister/interface) & spinner
progressbar 5 20
BLAH=$(cp files/service /etc/init.d/webister) & spinner
progressbar 6 20
BLAH=$(cp files/grabpass.php /etc/init.d/grabpass.php) & spinner
progressbar 7 20
BLAH=$(chmod +x /etc/init.d/webister) & spinner
progressbar 8 20
BLAH=$(service mysql start) & spinner
progressbar 9 20
BLAH=$(sudo adduser webister sudo) & spinner
progressbar 10 20
BLAH=$(usermod -aG sudo  webister) & spinner
progressbar 11 20
BLAH=$(cp -R website /var/webister/80) & spinner
progressbar 15 20
BLAH=$(chmod -R 777 /var/webister/80/) & spinner
progressbar 17 20
BLAH=$(php install.php $PASS) & spinner
progressbar 19 20
if /etc/init.d/webister start; then
    echo ""
else
    echo "Service: Exit code of $?, failure!!"
    exit 1
fi
progressbar 20 20
echo -e "\nThe installation is now complete."
echo -e "###############################################################################"

echo "Your system has installed Webister $VERSION"
echo "The system has detected which has been installed (This may not be correct)"
check () {
   if [ -n "$(command -v "$1")" ]; then
echo -e "$1: OK"
else
echo -e "$1: Not Installed, you may have issues."
fi
}
check php
check mysql
check telnet
echo "The default username and password is admin"
echo "Visit the control panel at port 8081."
echo -e "###############################################################################"
echo -e "###############################################################################"
